Repository UNO-Coders/Machine-Learning-Using-Python, pull requests merged in 2022-10, with the labels that each got.

#12 Matplot Basic Programs with example
  matplot/basic pyplot.py
  matplot/matplot-scipy.py
  matplot/predict_fun.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022, matplotlib

#13 Test-Train Split Visualization with Matplotlib
  matplot/test-train-split-visualization-witm-matplot.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022, matplotlib

#14 New Section - Data Science Projects
  Data Science Projects/Comcast Telecom Complaints/Comcast_telecom_complaints_data.csv
  Data Science Projects/Comcast Telecom Complaints/project.html
  Data Science Projects/Comcast Telecom Complaints/project.ipynb
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#16 New Project - Data Science Projects
  Data Science Projects/Lending Club/loan_data.csv
  Data Science Projects/Lending Club/project.html
  Data Science Projects/Lending Club/project.ipynb
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022, deep learning

#17 New Project - Data Science Projects
  Data Science Projects/Healthcare Capstone/corr_mat.xlsx
  Data Science Projects/Healthcare Capstone/dashboard.jpg
  Data Science Projects/Healthcare Capstone/health care diabetes.csv
  Data Science Projects/Healthcare Capstone/health care diabetes.xlsx
  Data Science Projects/Healthcare Capstone/project.html
  Data Science Projects/Healthcare Capstone/project.ipynb
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022, deep learning
